export const UserActionTypes = {
  SET_CURRENT_USER: "SET_CURRENT_USER",

  //Tried_sign_in_using_saga
  GOOGLE_SIGN_IN_START: "GOOGLE_SIGN_IN_START",
  SIGN_IN_START_SUCCESS: "SIGN_IN_START_SUCCESS",
  SIGN_IN_START_FAILURE: "SIGN_IN_START_FAILURE",

  EMAIL_SIGN_IN_START: "EMAIL_SIGN_IN_START",
};
